spring:
  application:
    name: user
server:
  port: 8094
say-hello:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8092,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000
